version: '3.8'

services:
  client:
    image: hamaaa/mern-client:latest
    environment:
      - API_URL=${API_URL}
    ports:
      - '3000:8080'
    depends_on:
      - server

  server:
    image: hamaaa/mern-server:latest
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - CLIENT_URL=${CLIENT_URL}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
      - FACEBOOK_CALLBACK_URL=${FACEBOOK_CALLBACK_URL}
    ports:
      - '5000:5000'
