apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-server
  namespace: mern-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mern-server
  template:
    metadata:
      labels:
        app: mern-server
    spec:
      containers:
      - name: server
        image: hamaaa/mern-server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mern-secrets
              key: MONGO_URI
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: mern-secrets
              key: JWT_SECRET
        - name: CLIENT_URL
          valueFrom:
            configMapKeyRef:
              name: mern-config
              key: CLIENT_URL
        - name: GOOGLE_CALLBACK_URL
          valueFrom:
            configMapKeyRef:
              name: mern-config
              key: GOOGLE_CALLBACK_URL
        - name: FACEBOOK_CALLBACK_URL
          valueFrom:
            configMapKeyRef:
              name: mern-config
              key: FACEBOOK_CALLBACK_URL
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
